In [34]:
from numpy import *
import numpy as np
from scipy import linalg

# 设置矩阵
def Hilbert(n):
    hilbert = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            hilbert[i][j]=1/(i+j+1)
    return np.mat(hilbert)

def SequentialGauss(mat_a):
    for i in range(0, (mat_a.shape[0]) - 1):
        if mat_a[i, i] == 0:
            print("中断运算：")
            print(mat_a)
            break
        else:
            for j in range(i + 1, mat_a.shape[0]):
                mat_a[j:j+1 , :] = mat_a[j:j+1,:] - (mat_a[j,i]/mat_a[i,i])*mat_a[i, :]
    return mat_a

# 回带过程
def revert(new_mat):
    #创建矩阵存放答案 初始化为0
    x = np.mat(np.zeros(new_mat.shape[0], dtype=float))
    number = x.shape[1] - 1
    # print(number)
    b = number + 1
    x[0, number] = new_mat[number, b] / new_mat[number, number]
    for i in range(number - 1, -1, -1):
        try:
            x[0, i] = (new_mat[i, b] - np.sum(np.multiply(new_mat[i, i + 1:b], x[0, i + 1:b]))) / (new_mat[i, i])
        except:
            print("错误")
    print(x)
    return x

np.set_printoptions(precision=3, suppress=True)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
# 第一题
# 合并两个矩阵
for n in [2,5,10]:
    print("n为%d时：\n"%n)
    mat_a = Hilbert(n)
    mat_b = np.mat(np.ones(n).T)
    new_mat = SequentialGauss(np.hstack((mat_a, mat_b.T)))

    print("求解得到三角矩阵为")
    print(new_mat)

    print("使用Guass消元法得到的方程的解为:")
    revert(new_mat)
    print('\n')

n为2时：

求解得到三角矩阵为
[[ 1.000  0.500  1.000]
 [ 0.000  0.083  0.500]]
使用Guass消元法得到的方程的解为:
[[-2.000  6.000]]


n为5时：

求解得到三角矩阵为
[[ 1.000  0.500  0.333  0.250  0.200  1.000]
 [ 0.000  0.083  0.083  0.075  0.067  0.500]
 [ 0.000 -0.000  0.006  0.008  0.010  0.167]
 [ 0.000  0.000  0.000  0.000  0.001  0.050]
 [ 0.000 -0.000  0.000  0.000  0.000  0.014]]
使用Guass消元法得到的方程的解为:
[[ 5.000 -120.000  630.000 -1120.000  630.000]]


n为10时：

求解得到三角矩阵为
[[ 1.000  0.500  0.333  0.250  0.200  0.167  0.143  0.125  0.111  0.100
   1.000]
 [ 0.000  0.083  0.083  0.075  0.067  0.060  0.054  0.049  0.044  0.041
   0.500]
 [ 0.000 -0.000  0.006  0.008  0.010  0.010  0.010  0.010  0.009  0.009
   0.167]
 [ 0.000  0.000  0.000  0.000  0.001  0.001  0.001  0.001  0.001  0.001
   0.050]
 [ 0.000 -0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
   0.014]
 [ 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
   0.004]
 [ 0.000 -0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000